/* 생성됨 — tools/gen_shaders.py (직접 고치지 말 것). 업스케일러마다 한 프로그램. */
#ifndef DISPLAY_SHADERS_H
#define DISPLAY_SHADERS_H
#define DISP_N_UP 5
static const char FS_UP_NONE[] =
   "/* Legacito 화면 셰이더 — 공통 머리. 한 패스: (업스케일러 → 섞기) → 필터들(세기별) → 출력.\n"
   "   좌표 p = vUV * uSize 는 «게임 픽셀 단위»(픽셀 가운데 = .5). 텍스처는 NEAREST 라 px() 로 칸을 직접 집는다. */\n"
   "#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
   "precision highp float;\n"
   "#else\n"
   "precision mediump float;\n"
   "#endif\n"
   "varying vec2 vUV;\n"
   "uniform sampler2D uTex;\n"
   "uniform vec2 uSize;     /* 게임 그림 크기(픽셀) */\n"
   "uniform vec2 uOut;      /* 화면에 그려지는 크기(픽셀) */\n"
   "uniform float uUpMix;   /* 업스케일러 섞기 0..1 (0 = 도트 그대로) */\n"
   "uniform float uGrid;    /* LCD 격자 세기 */\n"
   "uniform float uScan;    /* 스캔라인 세기 */\n"
   "uniform float uColor;   /* LCD 색감 세기 */\n"
   "uniform float uSoft;    /* 부드럽게(번짐) 세기 */\n"
   "vec3 px(vec2 t) { return texture2D(uTex, (clamp(t, vec2(0.0), uSize - 1.0) + 0.5) / uSize).rgb; }\n"
   "vec3 bil(vec2 p) {\n"
   "    vec2 q = p - 0.5; vec2 i = floor(q); vec2 f = q - i;\n"
   "    return mix(mix(px(i), px(i + vec2(1.0, 0.0)), f.x),\n"
   "               mix(px(i + vec2(0.0, 1.0)), px(i + vec2(1.0, 1.0)), f.x), f.y);\n"
   "}\n"
   "\n"
   "/* 업스케일러 없음 — 도트 그대로 */\n"
   "vec3 up(vec2 p) { return px(floor(p)); }\n"
   "\n"
   "void main() {\n"
   "    vec2 p = vUV * uSize;\n"
   "    vec3 nn = px(floor(p));\n"
   "    vec3 c = uUpMix > 0.0 ? mix(nn, up(p), uUpMix) : nn;\n"
   "    if (uSoft > 0.0) c = mix(c, bil(p), uSoft);\n"
   "    if (uColor > 0.0) {                                   /* LCD 색감: 채도·대비를 조금 눌러 실기 화면처럼 */\n"
   "        vec3 l = vec3(dot(c, vec3(0.299, 0.587, 0.114)));\n"
   "        vec3 lcd = pow(mix(l, c, 0.80), vec3(1.12)) * 0.92 + vec3(0.045, 0.05, 0.035);\n"
   "        c = mix(c, lcd, uColor);\n"
   "    }\n"
   "    vec2 sc = uOut / uSize;                               /* 게임 픽셀 하나 = 화면 몇 픽셀 */\n"
   "    vec2 f = fract(p);\n"
   "    if (uGrid > 0.0) {                                    /* LCD 격자: 칸 사이 가는 어두운 줄 */\n"
   "        vec2 e = min(f, 1.0 - f) * sc;\n"
   "        float w = max(1.0, min(sc.x, sc.y) * 0.10);\n"
   "        float g = 1.0 - smoothstep(w * 0.5 - 0.5, w * 0.5 + 0.5, min(e.x, e.y));\n"
   "        c *= 1.0 - uGrid * 0.6 * g;\n"
   "    }\n"
   "    if (uScan > 0.0) {                                    /* 스캔라인: 줄마다 아래위를 어둡게 */\n"
   "        float d = abs(f.y - 0.5) * 2.0;\n"
   "        c *= 1.0 - uScan * 0.55 * smoothstep(0.45, 1.0, d);\n"
   "    }\n"
   "    gl_FragColor = vec4(c, 1.0);\n"
   "}\n"
   "\n";
static const char FS_UP_SHARP[] =
   "/* Legacito 화면 셰이더 — 공통 머리. 한 패스: (업스케일러 → 섞기) → 필터들(세기별) → 출력.\n"
   "   좌표 p = vUV * uSize 는 «게임 픽셀 단위»(픽셀 가운데 = .5). 텍스처는 NEAREST 라 px() 로 칸을 직접 집는다. */\n"
   "#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
   "precision highp float;\n"
   "#else\n"
   "precision mediump float;\n"
   "#endif\n"
   "varying vec2 vUV;\n"
   "uniform sampler2D uTex;\n"
   "uniform vec2 uSize;     /* 게임 그림 크기(픽셀) */\n"
   "uniform vec2 uOut;      /* 화면에 그려지는 크기(픽셀) */\n"
   "uniform float uUpMix;   /* 업스케일러 섞기 0..1 (0 = 도트 그대로) */\n"
   "uniform float uGrid;    /* LCD 격자 세기 */\n"
   "uniform float uScan;    /* 스캔라인 세기 */\n"
   "uniform float uColor;   /* LCD 색감 세기 */\n"
   "uniform float uSoft;    /* 부드럽게(번짐) 세기 */\n"
   "vec3 px(vec2 t) { return texture2D(uTex, (clamp(t, vec2(0.0), uSize - 1.0) + 0.5) / uSize).rgb; }\n"
   "vec3 bil(vec2 p) {\n"
   "    vec2 q = p - 0.5; vec2 i = floor(q); vec2 f = q - i;\n"
   "    return mix(mix(px(i), px(i + vec2(1.0, 0.0)), f.x),\n"
   "               mix(px(i + vec2(0.0, 1.0)), px(i + vec2(1.0, 1.0)), f.x), f.y);\n"
   "}\n"
   "\n"
   "/* 샤프 바이리니어 — 정수배까지는 도트 그대로, 남는 소수 배율만 칸 경계에서 부드럽게(칸 크기 들쭉날쭉 없앰) */\n"
   "vec3 up(vec2 p) {\n"
   "    vec2 sc = max(floor(uOut / uSize), 1.0);\n"
   "    vec2 fl = floor(p);\n"
   "    vec2 cd = (p - fl) - 0.5;\n"
   "    vec2 rr = 0.5 - 0.5 / sc;\n"
   "    vec2 ff = (cd - clamp(cd, -rr, rr)) * sc + 0.5;\n"
   "    return bil(fl + ff);\n"
   "}\n"
   "\n"
   "void main() {\n"
   "    vec2 p = vUV * uSize;\n"
   "    vec3 nn = px(floor(p));\n"
   "    vec3 c = uUpMix > 0.0 ? mix(nn, up(p), uUpMix) : nn;\n"
   "    if (uSoft > 0.0) c = mix(c, bil(p), uSoft);\n"
   "    if (uColor > 0.0) {                                   /* LCD 색감: 채도·대비를 조금 눌러 실기 화면처럼 */\n"
   "        vec3 l = vec3(dot(c, vec3(0.299, 0.587, 0.114)));\n"
   "        vec3 lcd = pow(mix(l, c, 0.80), vec3(1.12)) * 0.92 + vec3(0.045, 0.05, 0.035);\n"
   "        c = mix(c, lcd, uColor);\n"
   "    }\n"
   "    vec2 sc = uOut / uSize;                               /* 게임 픽셀 하나 = 화면 몇 픽셀 */\n"
   "    vec2 f = fract(p);\n"
   "    if (uGrid > 0.0) {                                    /* LCD 격자: 칸 사이 가는 어두운 줄 */\n"
   "        vec2 e = min(f, 1.0 - f) * sc;\n"
   "        float w = max(1.0, min(sc.x, sc.y) * 0.10);\n"
   "        float g = 1.0 - smoothstep(w * 0.5 - 0.5, w * 0.5 + 0.5, min(e.x, e.y));\n"
   "        c *= 1.0 - uGrid * 0.6 * g;\n"
   "    }\n"
   "    if (uScan > 0.0) {                                    /* 스캔라인: 줄마다 아래위를 어둡게 */\n"
   "        float d = abs(f.y - 0.5) * 2.0;\n"
   "        c *= 1.0 - uScan * 0.55 * smoothstep(0.45, 1.0, d);\n"
   "    }\n"
   "    gl_FragColor = vec4(c, 1.0);\n"
   "}\n"
   "\n";
static const char FS_UP_SCALE2X[] =
   "/* Legacito 화면 셰이더 — 공통 머리. 한 패스: (업스케일러 → 섞기) → 필터들(세기별) → 출력.\n"
   "   좌표 p = vUV * uSize 는 «게임 픽셀 단위»(픽셀 가운데 = .5). 텍스처는 NEAREST 라 px() 로 칸을 직접 집는다. */\n"
   "#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
   "precision highp float;\n"
   "#else\n"
   "precision mediump float;\n"
   "#endif\n"
   "varying vec2 vUV;\n"
   "uniform sampler2D uTex;\n"
   "uniform vec2 uSize;     /* 게임 그림 크기(픽셀) */\n"
   "uniform vec2 uOut;      /* 화면에 그려지는 크기(픽셀) */\n"
   "uniform float uUpMix;   /* 업스케일러 섞기 0..1 (0 = 도트 그대로) */\n"
   "uniform float uGrid;    /* LCD 격자 세기 */\n"
   "uniform float uScan;    /* 스캔라인 세기 */\n"
   "uniform float uColor;   /* LCD 색감 세기 */\n"
   "uniform float uSoft;    /* 부드럽게(번짐) 세기 */\n"
   "vec3 px(vec2 t) { return texture2D(uTex, (clamp(t, vec2(0.0), uSize - 1.0) + 0.5) / uSize).rgb; }\n"
   "vec3 bil(vec2 p) {\n"
   "    vec2 q = p - 0.5; vec2 i = floor(q); vec2 f = q - i;\n"
   "    return mix(mix(px(i), px(i + vec2(1.0, 0.0)), f.x),\n"
   "               mix(px(i + vec2(0.0, 1.0)), px(i + vec2(1.0, 1.0)), f.x), f.y);\n"
   "}\n"
   "\n"
   "/* Scale2x(EPX) — 칸 하나를 넷으로 나눠, 이웃 둘이 같은 색으로 모서리를 이루면 그 색으로 계단을 깎는다.\n"
   "   (Eric Johnston 의 EPX / Scale2x 규칙을 그대로 옮겨 적음) */\n"
   "bool eqc(vec3 a, vec3 b) { vec3 d = abs(a - b); return d.r + d.g + d.b < 0.01; }\n"
   "vec3 up(vec2 p) {\n"
   "    vec2 c = floor(p); vec2 f = p - c;\n"
   "    vec3 E = px(c), B = px(c + vec2(0.0, -1.0)), D = px(c + vec2(-1.0, 0.0));\n"
   "    vec3 F = px(c + vec2(1.0, 0.0)), H = px(c + vec2(0.0, 1.0));\n"
   "    bool l = f.x < 0.5, t = f.y < 0.5;\n"
   "    if (t && l)  return (eqc(D, B) && !eqc(B, F) && !eqc(D, H)) ? D : E;\n"
   "    if (t)       return (eqc(B, F) && !eqc(B, D) && !eqc(F, H)) ? F : E;\n"
   "    if (l)       return (eqc(D, H) && !eqc(D, B) && !eqc(H, F)) ? D : E;\n"
   "    return (eqc(H, F) && !eqc(D, H) && !eqc(B, F)) ? F : E;\n"
   "}\n"
   "\n"
   "void main() {\n"
   "    vec2 p = vUV * uSize;\n"
   "    vec3 nn = px(floor(p));\n"
   "    vec3 c = uUpMix > 0.0 ? mix(nn, up(p), uUpMix) : nn;\n"
   "    if (uSoft > 0.0) c = mix(c, bil(p), uSoft);\n"
   "    if (uColor > 0.0) {                                   /* LCD 색감: 채도·대비를 조금 눌러 실기 화면처럼 */\n"
   "        vec3 l = vec3(dot(c, vec3(0.299, 0.587, 0.114)));\n"
   "        vec3 lcd = pow(mix(l, c, 0.80), vec3(1.12)) * 0.92 + vec3(0.045, 0.05, 0.035);\n"
   "        c = mix(c, lcd, uColor);\n"
   "    }\n"
   "    vec2 sc = uOut / uSize;                               /* 게임 픽셀 하나 = 화면 몇 픽셀 */\n"
   "    vec2 f = fract(p);\n"
   "    if (uGrid > 0.0) {                                    /* LCD 격자: 칸 사이 가는 어두운 줄 */\n"
   "        vec2 e = min(f, 1.0 - f) * sc;\n"
   "        float w = max(1.0, min(sc.x, sc.y) * 0.10);\n"
   "        float g = 1.0 - smoothstep(w * 0.5 - 0.5, w * 0.5 + 0.5, min(e.x, e.y));\n"
   "        c *= 1.0 - uGrid * 0.6 * g;\n"
   "    }\n"
   "    if (uScan > 0.0) {                                    /* 스캔라인: 줄마다 아래위를 어둡게 */\n"
   "        float d = abs(f.y - 0.5) * 2.0;\n"
   "        c *= 1.0 - uScan * 0.55 * smoothstep(0.45, 1.0, d);\n"
   "    }\n"
   "    gl_FragColor = vec4(c, 1.0);\n"
   "}\n"
   "\n";
static const char FS_UP_XBR[] =
   "/* Legacito 화면 셰이더 — 공통 머리. 한 패스: (업스케일러 → 섞기) → 필터들(세기별) → 출력.\n"
   "   좌표 p = vUV * uSize 는 «게임 픽셀 단위»(픽셀 가운데 = .5). 텍스처는 NEAREST 라 px() 로 칸을 직접 집는다. */\n"
   "#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
   "precision highp float;\n"
   "#else\n"
   "precision mediump float;\n"
   "#endif\n"
   "varying vec2 vUV;\n"
   "uniform sampler2D uTex;\n"
   "uniform vec2 uSize;     /* 게임 그림 크기(픽셀) */\n"
   "uniform vec2 uOut;      /* 화면에 그려지는 크기(픽셀) */\n"
   "uniform float uUpMix;   /* 업스케일러 섞기 0..1 (0 = 도트 그대로) */\n"
   "uniform float uGrid;    /* LCD 격자 세기 */\n"
   "uniform float uScan;    /* 스캔라인 세기 */\n"
   "uniform float uColor;   /* LCD 색감 세기 */\n"
   "uniform float uSoft;    /* 부드럽게(번짐) 세기 */\n"
   "vec3 px(vec2 t) { return texture2D(uTex, (clamp(t, vec2(0.0), uSize - 1.0) + 0.5) / uSize).rgb; }\n"
   "vec3 bil(vec2 p) {\n"
   "    vec2 q = p - 0.5; vec2 i = floor(q); vec2 f = q - i;\n"
   "    return mix(mix(px(i), px(i + vec2(1.0, 0.0)), f.x),\n"
   "               mix(px(i + vec2(0.0, 1.0)), px(i + vec2(1.0, 1.0)), f.x), f.y);\n"
   "}\n"
   "\n"
   "/*\n"
   "   Hyllian's xBR-lv2 Shader\n"
   "\n"
   "   Copyright (C) 2011-2016 Hyllian - sergiogdb@gmail.com\n"
   "\n"
   "   Permission is hereby granted, free of charge, to any person obtaining a copy\n"
   "   of this software and associated documentation files (the \"Software\"), to deal\n"
   "   in the Software without restriction, including without limitation the rights\n"
   "   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
   "   copies of the Software, and to permit persons to whom the Software is\n"
   "   furnished to do so, subject to the following conditions:\n"
   "\n"
   "   The above copyright notice and this permission notice shall be included in\n"
   "   all copies or substantial portions of the Software.\n"
   "\n"
   "   THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
   "   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
   "   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
   "   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
   "   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
   "   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
   "   THE SOFTWARE.\n"
   "\n"
   "   Incorporates some of the ideas from SABR shader. Thanks to Joshua Street.\n"
   "\n"
   "   Legacito: libretro glsl-shaders 의 xbr-lv2.glsl(CORNER_C, SMOOTH_TIPS)을 한 패스·자유 배율로 옮겼다\n"
   "   (경계 너비 = 화면 1픽셀 — XBR_SCALE 대신 실제 배율). GLSL ES 1.00.\n"
   "*/\n"
   "float xbr_cdf(vec3 c1, vec3 c2) { vec3 d = abs(c1 - c2); return d.r + d.g + d.b; }\n"
   "vec4 xbr_df(vec4 A, vec4 B) { return abs(A - B); }\n"
   "vec4 xbr_diff(vec4 A, vec4 B) { return vec4(notEqual(A, B)); }\n"
   "vec4 xbr_eq(vec4 A, vec4 B) { return step(xbr_df(A, B), vec4(15.0)); }\n"
   "vec4 xbr_neq(vec4 A, vec4 B) { return vec4(1.0) - xbr_eq(A, B); }\n"
   "vec4 xbr_wd(vec4 a, vec4 b, vec4 c, vec4 d, vec4 e, vec4 f, vec4 g, vec4 h)\n"
   "{ return xbr_df(a, b) + xbr_df(a, c) + xbr_df(d, e) + xbr_df(d, f) + 4.0 * xbr_df(g, h); }\n"
   "\n"
   "vec3 up(vec2 p) {\n"
   "    const vec4 Ao = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
   "    const vec4 Bo = vec4( 1.0,  1.0, -1.0,-1.0 );\n"
   "    const vec4 Co = vec4( 1.5,  0.5, -0.5, 0.5 );\n"
   "    const vec4 Ax = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
   "    const vec4 Bx = vec4( 0.5,  2.0, -0.5,-2.0 );\n"
   "    const vec4 Cx = vec4( 1.0,  1.0, -0.5, 0.0 );\n"
   "    const vec4 Ay = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
   "    const vec4 By = vec4( 2.0,  0.5, -2.0,-0.5 );\n"
   "    const vec4 Cy = vec4( 2.0,  0.0, -1.0, 0.5 );\n"
   "    const vec4 Ci = vec4(0.25, 0.25, 0.25, 0.25);\n"
   "    const vec3 rgbw = vec3(14.352, 28.176, 5.472);\n"
   "\n"
   "    vec2 c0 = floor(p);\n"
   "    vec2 fp = p - c0;\n"
   "    float xs = max(min(uOut.x / uSize.x, uOut.y / uSize.y), 1.0);\n"
   "    vec4 delta   = vec4(1.0 / xs);\n"
   "    vec4 delta_l = vec4(0.5 / xs, 1.0 / xs, 0.5 / xs, 1.0 / xs);\n"
   "    vec4 delta_u = delta_l.yxwz;\n"
   "\n"
   "    vec3 A1 = px(c0 + vec2(-1.0, -2.0)), B1 = px(c0 + vec2(0.0, -2.0)), C1 = px(c0 + vec2(1.0, -2.0));\n"
   "    vec3 A  = px(c0 + vec2(-1.0, -1.0)), B  = px(c0 + vec2(0.0, -1.0)), C  = px(c0 + vec2(1.0, -1.0));\n"
   "    vec3 D  = px(c0 + vec2(-1.0,  0.0)), E  = px(c0),                    F  = px(c0 + vec2(1.0,  0.0));\n"
   "    vec3 G  = px(c0 + vec2(-1.0,  1.0)), H  = px(c0 + vec2(0.0,  1.0)), I  = px(c0 + vec2(1.0,  1.0));\n"
   "    vec3 G5 = px(c0 + vec2(-1.0,  2.0)), H5 = px(c0 + vec2(0.0,  2.0)), I5 = px(c0 + vec2(1.0,  2.0));\n"
   "    vec3 A0 = px(c0 + vec2(-2.0, -1.0)), D0 = px(c0 + vec2(-2.0, 0.0)), G0 = px(c0 + vec2(-2.0, 1.0));\n"
   "    vec3 C4 = px(c0 + vec2( 2.0, -1.0)), F4 = px(c0 + vec2( 2.0, 0.0)), I4 = px(c0 + vec2( 2.0, 1.0));\n"
   "\n"
   "    vec4 b = vec4(dot(B, rgbw), dot(D, rgbw), dot(H, rgbw), dot(F, rgbw));\n"
   "    vec4 c = vec4(dot(C, rgbw), dot(A, rgbw), dot(G, rgbw), dot(I, rgbw));\n"
   "    vec4 d = b.yzwx;\n"
   "    vec4 e = vec4(dot(E, rgbw));\n"
   "    vec4 f = b.wxyz;\n"
   "    vec4 g = c.zwxy;\n"
   "    vec4 h = b.zwxy;\n"
   "    vec4 i = c.wxyz;\n"
   "    vec4 i4 = vec4(dot(I4, rgbw), dot(C1, rgbw), dot(A0, rgbw), dot(G5, rgbw));\n"
   "    vec4 i5 = vec4(dot(I5, rgbw), dot(C4, rgbw), dot(A1, rgbw), dot(G0, rgbw));\n"
   "    vec4 h5 = vec4(dot(H5, rgbw), dot(F4, rgbw), dot(B1, rgbw), dot(D0, rgbw));\n"
   "    vec4 f4 = h5.yzwx;\n"
   "\n"
   "    vec4 fx   = Ao * fp.y + Bo * fp.x;\n"
   "    vec4 fx_l = Ax * fp.y + Bx * fp.x;\n"
   "    vec4 fx_u = Ay * fp.y + By * fp.x;\n"
   "\n"
   "    vec4 irlv0 = xbr_diff(e, f) * xbr_diff(e, h);\n"
   "    vec4 irlv1 = irlv0 * (xbr_neq(f, b) * xbr_neq(f, c) + xbr_neq(h, d) * xbr_neq(h, g)\n"
   "               + xbr_eq(e, i) * (xbr_neq(f, f4) * xbr_neq(f, i4) + xbr_neq(h, h5) * xbr_neq(h, i5))\n"
   "               + xbr_eq(e, g) + xbr_eq(e, c));\n"
   "    vec4 irlv2l = xbr_diff(e, g) * xbr_diff(d, g);\n"
   "    vec4 irlv2u = xbr_diff(e, c) * xbr_diff(b, c);\n"
   "\n"
   "    vec4 fx45i = clamp((fx   + delta   - Co - Ci) / (2.0 * delta  ), 0.0, 1.0);\n"
   "    vec4 fx45  = clamp((fx   + delta   - Co     ) / (2.0 * delta  ), 0.0, 1.0);\n"
   "    vec4 fx30  = clamp((fx_l + delta_l - Cx     ) / (2.0 * delta_l), 0.0, 1.0);\n"
   "    vec4 fx60  = clamp((fx_u + delta_u - Cy     ) / (2.0 * delta_u), 0.0, 1.0);\n"
   "\n"
   "    vec4 wd1 = xbr_wd(e, c,  g, i, h5, f4, h, f);\n"
   "    vec4 wd2 = xbr_wd(h, d, i5, f, i4,  b, e, i);\n"
   "\n"
   "    vec4 edri  = step(wd1, wd2) * irlv0;\n"
   "    vec4 edr   = step(wd1 + vec4(0.1), wd2) * step(vec4(0.5), irlv1);\n"
   "    vec4 edr_l = step(2.0 * xbr_df(f, g), xbr_df(h, c)) * irlv2l * edr;\n"
   "    vec4 edr_u = step(2.0 * xbr_df(h, c), xbr_df(f, g)) * irlv2u * edr;\n"
   "\n"
   "    fx45  = edr   * fx45;\n"
   "    fx30  = edr_l * fx30;\n"
   "    fx60  = edr_u * fx60;\n"
   "    fx45i = edri  * fx45i;\n"
   "\n"
   "    vec4 pxs = step(xbr_df(e, f), xbr_df(e, h));\n"
   "    vec4 maximos = max(max(fx30, fx60), max(fx45, fx45i));\n"
   "\n"
   "    vec3 res1 = E;\n"
   "    res1 = mix(res1, mix(H, F, pxs.x), maximos.x);\n"
   "    res1 = mix(res1, mix(B, D, pxs.z), maximos.z);\n"
   "    vec3 res2 = E;\n"
   "    res2 = mix(res2, mix(F, B, pxs.y), maximos.y);\n"
   "    res2 = mix(res2, mix(D, H, pxs.w), maximos.w);\n"
   "    return mix(res1, res2, step(xbr_cdf(E, res1), xbr_cdf(E, res2)));\n"
   "}\n"
   "\n"
   "void main() {\n"
   "    vec2 p = vUV * uSize;\n"
   "    vec3 nn = px(floor(p));\n"
   "    vec3 c = uUpMix > 0.0 ? mix(nn, up(p), uUpMix) : nn;\n"
   "    if (uSoft > 0.0) c = mix(c, bil(p), uSoft);\n"
   "    if (uColor > 0.0) {                                   /* LCD 색감: 채도·대비를 조금 눌러 실기 화면처럼 */\n"
   "        vec3 l = vec3(dot(c, vec3(0.299, 0.587, 0.114)));\n"
   "        vec3 lcd = pow(mix(l, c, 0.80), vec3(1.12)) * 0.92 + vec3(0.045, 0.05, 0.035);\n"
   "        c = mix(c, lcd, uColor);\n"
   "    }\n"
   "    vec2 sc = uOut / uSize;                               /* 게임 픽셀 하나 = 화면 몇 픽셀 */\n"
   "    vec2 f = fract(p);\n"
   "    if (uGrid > 0.0) {                                    /* LCD 격자: 칸 사이 가는 어두운 줄 */\n"
   "        vec2 e = min(f, 1.0 - f) * sc;\n"
   "        float w = max(1.0, min(sc.x, sc.y) * 0.10);\n"
   "        float g = 1.0 - smoothstep(w * 0.5 - 0.5, w * 0.5 + 0.5, min(e.x, e.y));\n"
   "        c *= 1.0 - uGrid * 0.6 * g;\n"
   "    }\n"
   "    if (uScan > 0.0) {                                    /* 스캔라인: 줄마다 아래위를 어둡게 */\n"
   "        float d = abs(f.y - 0.5) * 2.0;\n"
   "        c *= 1.0 - uScan * 0.55 * smoothstep(0.45, 1.0, d);\n"
   "    }\n"
   "    gl_FragColor = vec4(c, 1.0);\n"
   "}\n"
   "\n";
static const char FS_UP_OMNI[] =
   "/* Legacito 화면 셰이더 — 공통 머리. 한 패스: (업스케일러 → 섞기) → 필터들(세기별) → 출력.\n"
   "   좌표 p = vUV * uSize 는 «게임 픽셀 단위»(픽셀 가운데 = .5). 텍스처는 NEAREST 라 px() 로 칸을 직접 집는다. */\n"
   "#ifdef GL_FRAGMENT_PRECISION_HIGH\n"
   "precision highp float;\n"
   "#else\n"
   "precision mediump float;\n"
   "#endif\n"
   "varying vec2 vUV;\n"
   "uniform sampler2D uTex;\n"
   "uniform vec2 uSize;     /* 게임 그림 크기(픽셀) */\n"
   "uniform vec2 uOut;      /* 화면에 그려지는 크기(픽셀) */\n"
   "uniform float uUpMix;   /* 업스케일러 섞기 0..1 (0 = 도트 그대로) */\n"
   "uniform float uGrid;    /* LCD 격자 세기 */\n"
   "uniform float uScan;    /* 스캔라인 세기 */\n"
   "uniform float uColor;   /* LCD 색감 세기 */\n"
   "uniform float uSoft;    /* 부드럽게(번짐) 세기 */\n"
   "vec3 px(vec2 t) { return texture2D(uTex, (clamp(t, vec2(0.0), uSize - 1.0) + 0.5) / uSize).rgb; }\n"
   "vec3 bil(vec2 p) {\n"
   "    vec2 q = p - 0.5; vec2 i = floor(q); vec2 f = q - i;\n"
   "    return mix(mix(px(i), px(i + vec2(1.0, 0.0)), f.x),\n"
   "               mix(px(i + vec2(0.0, 1.0)), px(i + vec2(1.0, 1.0)), f.x), f.y);\n"
   "}\n"
   "\n"
   "/*\n"
   "OmniScale\n"
   "by Lior Halphon (ported to RetroArch glsl by hunterk)\n"
   "\n"
   "MIT License\n"
   "\n"
   "Copyright (c) 2015-2016 Lior Halphon\n"
   "\n"
   "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
   "of this software and associated documentation files (the \"Software\"), to deal\n"
   "in the Software without restriction, including without limitation the rights\n"
   "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
   "copies of the Software, and to permit persons to whom the Software is\n"
   "furnished to do so, subject to the following conditions:\n"
   "\n"
   "The above copyright notice and this permission notice shall be included in all\n"
   "copies or substantial portions of the Software.\n"
   "\n"
   "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
   "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
   "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
   "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
   "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
   "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
   "SOFTWARE.\n"
   "\n"
   "Legacito: GLSL ES 1.00 엔 비트 연산이 없어 P(m, r) 패턴 검사를 생성기(tools/gen_shaders.py)가 불 대수로 펼쳤다.\n"
   "이웃은 칸 단위로 집는다(px). 출력은 vec3.\n"
   "*/\n"
   "vec3 om_hq(vec3 rgb) {\n"
   "    return vec3( 0.250 * rgb.r + 0.250 * rgb.g + 0.250 * rgb.b,\n"
   "                 0.250 * rgb.r - 0.000 * rgb.g - 0.250 * rgb.b,\n"
   "                -0.125 * rgb.r + 0.250 * rgb.g - 0.125 * rgb.b);\n"
   "}\n"
   "bool om_diff(vec3 a, vec3 b) {\n"
   "    vec3 d = abs(om_hq(a) - om_hq(b));\n"
   "    return d.x > 0.125 || d.y > 0.027 || d.z > 0.031;\n"
   "}\n"
   "vec3 up(vec2 pos) {\n"
   "    vec2 c = floor(pos);\n"
   "    vec2 o = vec2(1.0);\n"
   "    vec2 p = pos - c;\n"
   "    if (p.x > 0.5) { o.x = -o.x; p.x = 1.0 - p.x; }\n"
   "    if (p.y > 0.5) { o.y = -o.y; p.y = 1.0 - p.y; }\n"
   "    vec3 w0 = px(c + vec2(-o.x, -o.y));\n"
   "    vec3 w1 = px(c + vec2( 0.0, -o.y));\n"
   "    vec3 w2 = px(c + vec2( o.x, -o.y));\n"
   "    vec3 w3 = px(c + vec2(-o.x,  0.0));\n"
   "    vec3 w4 = px(c);\n"
   "    vec3 w5 = px(c + vec2( o.x,  0.0));\n"
   "    vec3 w6 = px(c + vec2(-o.x,  o.y));\n"
   "    vec3 w7 = px(c + vec2( 0.0,  o.y));\n"
   "    vec3 w8 = px(c + vec2( o.x,  o.y));\n"
   "    bool d0 = om_diff(w0, w4), d1 = om_diff(w1, w4), d2 = om_diff(w2, w4), d3 = om_diff(w3, w4);\n"
   "    bool d4 = om_diff(w5, w4), d5 = om_diff(w6, w4), d6 = om_diff(w7, w4), d7 = om_diff(w8, w4);\n"
   "    float pixel_size = length(uSize / uOut);\n"
   "\n"
   "    if (((d0 && d1 && d2 && !d3 && d4 && d5 && !d7) || (d0 && d1 && !d3 && d4 && !d6 && !d7)) && om_diff(w1, w5))\n"
   "        return mix(w4, w3, 0.5 - p.x);\n"
   "    if (((d0 && !d1 && d3 && !d4 && d6 && !d7) || (d0 && !d1 && d2 && d3 && d5 && d6 && !d7)) && om_diff(w7, w3))\n"
   "        return mix(w4, w1, 0.5 - p.y);\n"
   "    if (((d0 && d1 && d3) || (d1 && !d2 && d3 && !d4 && !d5 && d6 && !d7) || (d1 && !d2 && d3 && d4 && !d5 && !d6 && !d7)) && om_diff(w3, w1))\n"
   "        return w4;\n"
   "    if (((!d0 && d1 && !d2 && d3 && d5 && !d6) || (!d0 && d1 && d3 && !d4 && !d6) || (!d0 && d1 && !d2 && d3 && d4 && d5 && !d7) || (!d0 && d1 && !d2 && d3 && d4 && d6 && !d7) ||\n"
   "         (!d0 && d1 && !d2 && d3 && !d4 && d7) || (!d0 && d1 && !d2 && d3 && !d6 && d7) || (!d0 && d1 && d2 && d3 && !d5 && d6 && !d7) || (!d0 && d1 && d2 && d3 && !d4 && !d5) ||\n"
   "         (!d0 && d1 && d3 && d4 && !d5 && d6 && !d7) || (!d0 && d1 && d3 && !d4 && !d5 && d7) || (!d0 && d1 && !d2 && d3 && d4 && !d5 && d6) || (!d0 && d1 && !d2 && d3 && !d5 && d7) ||\n"
   "         (!d0 && d1 && d3 && !d5 && !d6 && d7)) && om_diff(w3, w1))\n"
   "        return mix(w4, mix(w4, w0, 0.5 - p.x), 0.5 - p.y);\n"
   "    if ((!d0 && !d1 && d3))\n"
   "        return mix(mix(w0 * 0.375 + w1 * 0.25 + w4 * 0.375, w4 * 0.5 + w1 * 0.5, p.x * 2.0), w4, p.y * 2.0);\n"
   "    if ((!d0 && d1 && !d3))\n"
   "        return mix(mix(w0 * 0.375 + w3 * 0.25 + w4 * 0.375, w4 * 0.5 + w3 * 0.5, p.y * 2.0), w4, p.x * 2.0);\n"
   "    if ((d0 && d1 && d2 && d3 && d5)) {\n"
   "        float dist = length(p - vec2(0.5));\n"
   "        if (dist < 0.5 - pixel_size / 2.0) return w4;\n"
   "        vec3 r;\n"
   "        if (om_diff(w0, w1) || om_diff(w0, w3)) r = mix(w1, w3, p.y - p.x + 0.5);\n"
   "        else r = mix(mix(w1 * 0.375 + w0 * 0.25 + w3 * 0.375, w3, p.y * 2.0), w1, p.x * 2.0);\n"
   "        if (dist > 0.5 + pixel_size / 2.0) return r;\n"
   "        return mix(w4, r, (dist - 0.5 + pixel_size / 2.0) / pixel_size);\n"
   "    }\n"
   "    if ((d0 && d1 && d2 && !d3 && d4 && d5 && !d7) || (d0 && d1 && !d3 && d4 && !d6 && !d7)) {\n"
   "        float dist = p.x - 2.0 * p.y;\n"
   "        float ps5 = pixel_size * sqrt(5.0);\n"
   "        if (dist > ps5 / 2.0) return w1;\n"
   "        vec3 r = mix(w3, w4, p.x + 0.5);\n"
   "        if (dist < -ps5 / 2.0) return r;\n"
   "        return mix(r, w1, (dist + ps5 / 2.0) / ps5);\n"
   "    }\n"
   "    if ((d0 && !d1 && d3 && !d4 && d6 && !d7) || (d0 && !d1 && d2 && d3 && d5 && d6 && !d7)) {\n"
   "        float dist = p.y - 2.0 * p.x;\n"
   "        float ps5 = pixel_size * sqrt(5.0);\n"
   "        if (p.y - 2.0 * p.x > ps5 / 2.0) return w3;\n"
   "        vec3 r = mix(w1, w4, p.x + 0.5);\n"
   "        if (dist < -ps5 / 2.0) return r;\n"
   "        return mix(r, w3, (dist + ps5 / 2.0) / ps5);\n"
   "    }\n"
   "    if ((d0 && d1 && d2 && d3 && !d4 && !d5 && d7) || (d1 && d2 && d3 && !d4 && !d5 && !d6)) {\n"
   "        float dist = p.x + 2.0 * p.y;\n"
   "        float ps5 = pixel_size * sqrt(5.0);\n"
   "        if (dist > 1.0 + ps5 / 2.0) return w4;\n"
   "        vec3 r;\n"
   "        if (om_diff(w0, w1) || om_diff(w0, w3)) r = mix(w1, w3, p.y - p.x + 0.5);\n"
   "        else r = mix(mix(w1 * 0.375 + w0 * 0.25 + w3 * 0.375, w3, p.y * 2.0), w1, p.x * 2.0);\n"
   "        if (dist < 1.0 - ps5 / 2.0) return r;\n"
   "        return mix(r, w4, (dist + ps5 / 2.0 - 1.0) / ps5);\n"
   "    }\n"
   "    if ((d1 && !d2 && d3 && !d4 && d5 && !d6) || (d0 && d1 && !d2 && d3 && d5 && !d6 && d7)) {\n"
   "        float dist = p.y + 2.0 * p.x;\n"
   "        float ps5 = pixel_size * sqrt(5.0);\n"
   "        if (p.y + 2.0 * p.x > 1.0 + ps5 / 2.0) return w4;\n"
   "        vec3 r;\n"
   "        if (om_diff(w0, w1) || om_diff(w0, w3)) r = mix(w1, w3, p.y - p.x + 0.5);\n"
   "        else r = mix(mix(w1 * 0.375 + w0 * 0.25 + w3 * 0.375, w3, p.y * 2.0), w1, p.x * 2.0);\n"
   "        if (dist < 1.0 - ps5 / 2.0) return r;\n"
   "        return mix(r, w4, (dist + ps5 / 2.0 - 1.0) / ps5);\n"
   "    }\n"
   "    if ((d0 && d1 && !d3 && !d4) || (d0 && d1 && !d2 && !d3 && d6) || (d0 && d1 && !d3 && d7) || (d0 && d1 && !d3 && !d5 && d6))\n"
   "        return mix(w4, w3, 0.5 - p.x);\n"
   "    if ((d0 && !d1 && d3 && !d6) || (d0 && !d1 && d3 && d7) || (d0 && !d1 && !d2 && d3 && d4) || (d0 && !d1 && d3 && d4 && !d5))\n"
   "        return mix(w4, w1, 0.5 - p.y);\n"
   "    if ((!d0 && d1 && d3 && !d4 && d5 && d6 && !d7) || (!d0 && d1 && d2 && d3 && d5 && d6) || (!d0 && d1 && d2 && d3 && d4 && d5) || (!d0 && d1 && d3 && d4 && d5 && d6 && d7) ||\n"
   "        (!d0 && d1 && d2 && d3 && d4 && d6 && d7) || (!d0 && d1 && d2 && d3 && d4 && !d6 && !d7))\n"
   "        return mix(w4, w0, (1.0 - p.x - p.y) / 2.0);\n"
   "    if ((d0 && d1 && !d2 && d3 && d6) || (d0 && d1 && !d2 && d3 && d4 && !d7) || (d0 && d1 && !d2 && d3 && !d5) ||\n"
   "        (d1 && !d2 && d3 && !d4 && !d5 && !d7) || (d1 && !d2 && d3 && !d5 && !d6 && !d7) || (d1 && !d2 && d3 && !d4 && !d5 && !d6) || (d0 && d1 && d3 && !d5 && d6 && !d7) ||\n"
   "        (d0 && d1 && d3 && d4 && !d5)) {\n"
   "        float dist = p.x + p.y;\n"
   "        if (dist > 0.5 + pixel_size / 2.0) return w4;\n"
   "        vec3 r;\n"
   "        if (om_diff(w0, w1) || om_diff(w0, w3)) r = mix(w1, w3, p.y - p.x + 0.5);\n"
   "        else r = mix(mix(w1 * 0.375 + w0 * 0.25 + w3 * 0.375, w3, p.y * 2.0), w1, p.x * 2.0);\n"
   "        if (dist < 0.5 - pixel_size / 2.0) return r;\n"
   "        return mix(r, w4, (dist + pixel_size / 2.0 - 0.5) / pixel_size);\n"
   "    }\n"
   "    if ((d0 && !d1 && !d3))\n"
   "        return mix(mix(w4, w3, 0.5 - p.x), mix(w1, (w1 + w3) / 2.0, 0.5 - p.x), 0.5 - p.y);\n"
   "    if ((!d0 && !d1 && !d3))\n"
   "        return mix(mix(w4, w3, 0.5 - p.x), mix(w1, w0, 0.5 - p.x), 0.5 - p.y);\n"
   "\n"
   "    float dist = p.x + p.y;\n"
   "    if (dist > 0.5 + pixel_size / 2.0) return w4;\n"
   "\n"
   "    /* 대각선을 풀려면 이웃을 더 본다 — 다른 칸 수를 세어 기울기를 정한다(원본의 비트 세기) */\n"
   "    vec3 x0 = px(c + vec2(-o.x * 2.0, -o.y * 2.0));\n"
   "    vec3 x1 = px(c + vec2(-o.x,       -o.y * 2.0));\n"
   "    vec3 x2 = px(c + vec2( 0.0,       -o.y * 2.0));\n"
   "    vec3 x3 = px(c + vec2( o.x,       -o.y * 2.0));\n"
   "    vec3 x4 = px(c + vec2(-o.x * 2.0, -o.y      ));\n"
   "    vec3 x5 = px(c + vec2(-o.x * 2.0,  0.0      ));\n"
   "    vec3 x6 = px(c + vec2(-o.x * 2.0,  o.y      ));\n"
   "    float bias = -7.0\n"
   "        + (d0 ? 1.0 : 0.0) + (d1 ? 1.0 : 0.0) + (d2 ? 1.0 : 0.0) + (d3 ? 1.0 : 0.0)\n"
   "        + (d4 ? 1.0 : 0.0) + (d5 ? 1.0 : 0.0) + (d6 ? 1.0 : 0.0) + (d7 ? 1.0 : 0.0)\n"
   "        + (om_diff(x0, w4) ? 1.0 : 0.0) + (om_diff(x1, w4) ? 1.0 : 0.0) + (om_diff(x2, w4) ? 1.0 : 0.0)\n"
   "        + (om_diff(x3, w4) ? 1.0 : 0.0) + (om_diff(x4, w4) ? 1.0 : 0.0) + (om_diff(x5, w4) ? 1.0 : 0.0)\n"
   "        + (om_diff(x6, w4) ? 1.0 : 0.0);\n"
   "    if (bias <= 0.0) {\n"
   "        vec3 r = mix(w1, w3, p.y - p.x + 0.5);\n"
   "        if (dist < 0.5 - pixel_size / 2.0) return r;\n"
   "        return mix(r, w4, (dist + pixel_size / 2.0 - 0.5) / pixel_size);\n"
   "    }\n"
   "    return w4;\n"
   "}\n"
   "\n"
   "void main() {\n"
   "    vec2 p = vUV * uSize;\n"
   "    vec3 nn = px(floor(p));\n"
   "    vec3 c = uUpMix > 0.0 ? mix(nn, up(p), uUpMix) : nn;\n"
   "    if (uSoft > 0.0) c = mix(c, bil(p), uSoft);\n"
   "    if (uColor > 0.0) {                                   /* LCD 색감: 채도·대비를 조금 눌러 실기 화면처럼 */\n"
   "        vec3 l = vec3(dot(c, vec3(0.299, 0.587, 0.114)));\n"
   "        vec3 lcd = pow(mix(l, c, 0.80), vec3(1.12)) * 0.92 + vec3(0.045, 0.05, 0.035);\n"
   "        c = mix(c, lcd, uColor);\n"
   "    }\n"
   "    vec2 sc = uOut / uSize;                               /* 게임 픽셀 하나 = 화면 몇 픽셀 */\n"
   "    vec2 f = fract(p);\n"
   "    if (uGrid > 0.0) {                                    /* LCD 격자: 칸 사이 가는 어두운 줄 */\n"
   "        vec2 e = min(f, 1.0 - f) * sc;\n"
   "        float w = max(1.0, min(sc.x, sc.y) * 0.10);\n"
   "        float g = 1.0 - smoothstep(w * 0.5 - 0.5, w * 0.5 + 0.5, min(e.x, e.y));\n"
   "        c *= 1.0 - uGrid * 0.6 * g;\n"
   "    }\n"
   "    if (uScan > 0.0) {                                    /* 스캔라인: 줄마다 아래위를 어둡게 */\n"
   "        float d = abs(f.y - 0.5) * 2.0;\n"
   "        c *= 1.0 - uScan * 0.55 * smoothstep(0.45, 1.0, d);\n"
   "    }\n"
   "    gl_FragColor = vec4(c, 1.0);\n"
   "}\n"
   "\n";
static const char *const FS_UP[DISP_N_UP] = { FS_UP_NONE, FS_UP_SHARP, FS_UP_SCALE2X, FS_UP_XBR, FS_UP_OMNI };
#endif
